<?php
/**
 * Created by PhpStorm.
 * User: Georgy
 * Date: 25.05.2018
 * Time: 13:00
 */
include_once ('productShort.php');

class product extends productShort
{
    public $sku;
    public $vendor;
    public $category;
    public $title;
    public $pn;
    public $dateModified;
    public $popularity;
    public $price;

    public $heroPic;
    public $galleryPics = array();
    public $features = array();

    public function __construct($sku)
    {

        parent::__construct($sku);
    }

    public function callData($sku)
    {
        return parent::callData($sku); // TODO: Change the autogenerated stub
    }
}